CREATE TABLE IF NOT EXISTS weather_bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  market_id VARCHAR(255) NOT NULL,
  token_id VARCHAR(255) NOT NULL,
  order_id VARCHAR(255),
  city VARCHAR(50) NOT NULL,
  market_title TEXT NOT NULL,
  bracket_lower DECIMAL(5,1) NOT NULL,
  bracket_upper DECIMAL(5,1) NOT NULL,
  bracket_lower_c DECIMAL(5,2) NOT NULL,
  bracket_upper_c DECIMAL(5,2) NOT NULL,
  unit CHAR(1) NOT NULL,
  forecast_prob DECIMAL(5,4) NOT NULL,
  market_price DECIMAL(5,4) NOT NULL,
  edge DECIMAL(5,4) NOT NULL,
  bet_size DECIMAL(10,2) NOT NULL,
  entry_price DECIMAL(5,4) NOT NULL,
  fill_amount DECIMAL(10,2),
  gas_fee DECIMAL(10,4),
  status ENUM('PENDING','FILLED','PARTIALLY_FILLED','WON','LOST','CANCELLED','SIMULATED') NOT NULL,
  resolution_date DATE NOT NULL,
  outcome DECIMAL(5,1),
  pnl DECIMAL(10,2),
  phase ENUM('2a','2b','2c') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_resolution (resolution_date, status),
  INDEX idx_city_created (city, created_at)
);
