import type { CityConfig } from '../types/index.js';

export const CITIES: Record<string, CityConfig> = {
  NYC: {
    key: 'NYC',
    lat: 40.7829,
    lon: -73.9654,
    station: 'Central Park',
    timezone: 'America/New_York',
  },
  London: {
    key: 'London',
    lat: 51.505,
    lon: 0.055,
    station: 'EGLC',
    timezone: 'Europe/London',
  },
  Seoul: {
    key: 'Seoul',
    lat: 37.5665,
    lon: 126.978,
    station: 'KMA Seoul',
    timezone: 'Asia/Seoul',
  },
  Tokyo: {
    key: 'Tokyo',
    lat: 35.6762,
    lon: 139.6503,
    station: 'Tokyo',
    timezone: 'Asia/Tokyo',
  },
  Shanghai: {
    key: 'Shanghai',
    lat: 31.2304,
    lon: 121.4737,
    station: 'Shanghai',
    timezone: 'Asia/Shanghai',
  },
  Chicago: {
    key: 'Chicago',
    lat: 41.8781,
    lon: -87.6298,
    station: "O'Hare",
    timezone: 'America/Chicago',
  },
  Atlanta: {
    key: 'Atlanta',
    lat: 33.749,
    lon: -84.388,
    station: 'Atlanta Hartsfield',
    timezone: 'America/New_York',
  },
  Miami: {
    key: 'Miami',
    lat: 25.7617,
    lon: -80.1918,
    station: 'Miami Intl',
    timezone: 'America/New_York',
  },
  Warsaw: {
    key: 'Warsaw',
    lat: 52.2297,
    lon: 21.0122,
    station: 'Warsaw Chopin',
    timezone: 'Europe/Warsaw',
  },
  Toronto: {
    key: 'Toronto',
    lat: 43.6532,
    lon: -79.3832,
    station: 'Toronto Pearson',
    timezone: 'America/Toronto',
  },
  Paris: {
    key: 'Paris',
    lat: 48.8566,
    lon: 2.3522,
    station: 'Paris Orly',
    timezone: 'Europe/Paris',
  },
  Wellington: {
    key: 'Wellington',
    lat: -41.2865,
    lon: 174.7762,
    station: 'Wellington',
    timezone: 'Pacific/Auckland',
  },
  'Tel Aviv': {
    key: 'Tel Aviv',
    lat: 32.0853,
    lon: 34.7818,
    station: 'Ben Gurion',
    timezone: 'Asia/Jerusalem',
  },
  'Hong Kong': {
    key: 'Hong Kong',
    lat: 22.3193,
    lon: 114.1694,
    station: 'HK Observatory',
    timezone: 'Asia/Hong_Kong',
  },
};
